/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ImportHistoryRouteImport } from './routes/import-history'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as EscalationRouteImport } from './routes/escalation'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as AiCommanderRouteImport } from './routes/ai-commander'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonitorDevicesRouteImport } from './routes/monitor.devices'
import { Route as MonitorIdRouteImport } from './routes/monitor.$id'
import { Route as EvidencePlaybackRouteImport } from './routes/evidence.playback'
import { Route as ApiTimelineRouteImport } from './routes/api/timeline'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiSystemCorrelationRouteImport } from './routes/api/system.correlation'
import { Route as ApiMonitorStatusRouteImport } from './routes/api/monitor.status'
import { Route as ApiMonitorStateRouteImport } from './routes/api/monitor.state'
import { Route as ApiMonitorDevicesRouteImport } from './routes/api/monitor.devices'
import { Route as ApiEvidenceSnapshotsRouteImport } from './routes/api/evidence.snapshots'
import { Route as ApiAutopilotServicesRouteImport } from './routes/api/autopilot.services'
import { Route as ApiAutopilotRecommendationsRouteImport } from './routes/api/autopilot.recommendations'
import { Route as ApiAiRootCauseAssistRouteImport } from './routes/api/ai.root-cause-assist'
import { Route as ApiAutopilotServicesIdRouteImport } from './routes/api/autopilot.services.$id'
import { Route as ApiAutopilotRecommendationsIdRouteImport } from './routes/api/autopilot.recommendations.$id'
import { Route as ApiAlertsIdResolveRouteImport } from './routes/api/alerts.$id.resolve'
import { Route as ApiAlertsIdAckRouteImport } from './routes/api/alerts.$id.ack'
import { Route as ApiMonitorDevicesIdLogPathsRouteImport } from './routes/api/monitor.devices.$id.log-paths'
import { Route as ApiMonitorDevicesIdCorrelateRecentRouteImport } from './routes/api/monitor.devices.$id.correlate-recent'
import { Route as ApiAutopilotRecommendationsFromAlertAlertIdRouteImport } from './routes/api/autopilot.recommendations.from-alert.$alertId'
import { Route as ApiAutopilotRecommendationsIdRejectRouteImport } from './routes/api/autopilot.recommendations.$id.reject'
import { Route as ApiAutopilotRecommendationsIdApproveRouteImport } from './routes/api/autopilot.recommendations.$id.approve'
import { Route as ApiMonitorDevicesIdLogsRecentRouteImport } from './routes/api/monitor.devices.$id.logs.recent'

const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportHistoryRoute = ImportHistoryRouteImport.update({
  id: '/import-history',
  path: '/import-history',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationRoute = EscalationRouteImport.update({
  id: '/escalation',
  path: '/escalation',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCommanderRoute = AiCommanderRouteImport.update({
  id: '/ai-commander',
  path: '/ai-commander',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorDevicesRoute = MonitorDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => MonitorRoute,
} as any)
const MonitorIdRoute = MonitorIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MonitorRoute,
} as any)
const EvidencePlaybackRoute = EvidencePlaybackRouteImport.update({
  id: '/playback',
  path: '/playback',
  getParentRoute: () => EvidenceRoute,
} as any)
const ApiTimelineRoute = ApiTimelineRouteImport.update({
  id: '/api/timeline',
  path: '/api/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemCorrelationRoute = ApiSystemCorrelationRouteImport.update({
  id: '/api/system/correlation',
  path: '/api/system/correlation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitorStatusRoute = ApiMonitorStatusRouteImport.update({
  id: '/api/monitor/status',
  path: '/api/monitor/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitorStateRoute = ApiMonitorStateRouteImport.update({
  id: '/api/monitor/state',
  path: '/api/monitor/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitorDevicesRoute = ApiMonitorDevicesRouteImport.update({
  id: '/api/monitor/devices',
  path: '/api/monitor/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenceSnapshotsRoute = ApiEvidenceSnapshotsRouteImport.update({
  id: '/api/evidence/snapshots',
  path: '/api/evidence/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutopilotServicesRoute = ApiAutopilotServicesRouteImport.update({
  id: '/api/autopilot/services',
  path: '/api/autopilot/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutopilotRecommendationsRoute =
  ApiAutopilotRecommendationsRouteImport.update({
    id: '/api/autopilot/recommendations',
    path: '/api/autopilot/recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiRootCauseAssistRoute = ApiAiRootCauseAssistRouteImport.update({
  id: '/api/ai/root-cause-assist',
  path: '/api/ai/root-cause-assist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutopilotServicesIdRoute = ApiAutopilotServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAutopilotServicesRoute,
} as any)
const ApiAutopilotRecommendationsIdRoute =
  ApiAutopilotRecommendationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiAutopilotRecommendationsRoute,
  } as any)
const ApiAlertsIdResolveRoute = ApiAlertsIdResolveRouteImport.update({
  id: '/$id/resolve',
  path: '/$id/resolve',
  getParentRoute: () => ApiAlertsRoute,
} as any)
const ApiAlertsIdAckRoute = ApiAlertsIdAckRouteImport.update({
  id: '/$id/ack',
  path: '/$id/ack',
  getParentRoute: () => ApiAlertsRoute,
} as any)
const ApiMonitorDevicesIdLogPathsRoute =
  ApiMonitorDevicesIdLogPathsRouteImport.update({
    id: '/$id/log-paths',
    path: '/$id/log-paths',
    getParentRoute: () => ApiMonitorDevicesRoute,
  } as any)
const ApiMonitorDevicesIdCorrelateRecentRoute =
  ApiMonitorDevicesIdCorrelateRecentRouteImport.update({
    id: '/$id/correlate-recent',
    path: '/$id/correlate-recent',
    getParentRoute: () => ApiMonitorDevicesRoute,
  } as any)
const ApiAutopilotRecommendationsFromAlertAlertIdRoute =
  ApiAutopilotRecommendationsFromAlertAlertIdRouteImport.update({
    id: '/from-alert/$alertId',
    path: '/from-alert/$alertId',
    getParentRoute: () => ApiAutopilotRecommendationsRoute,
  } as any)
const ApiAutopilotRecommendationsIdRejectRoute =
  ApiAutopilotRecommendationsIdRejectRouteImport.update({
    id: '/reject',
    path: '/reject',
    getParentRoute: () => ApiAutopilotRecommendationsIdRoute,
  } as any)
const ApiAutopilotRecommendationsIdApproveRoute =
  ApiAutopilotRecommendationsIdApproveRouteImport.update({
    id: '/approve',
    path: '/approve',
    getParentRoute: () => ApiAutopilotRecommendationsIdRoute,
  } as any)
const ApiMonitorDevicesIdLogsRecentRoute =
  ApiMonitorDevicesIdLogsRecentRouteImport.update({
    id: '/$id/logs/recent',
    path: '/$id/logs/recent',
    getParentRoute: () => ApiMonitorDevicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-commander': typeof AiCommanderRoute
  '/autopilot': typeof AutopilotRoute
  '/diagnosis': typeof DiagnosisRoute
  '/escalation': typeof EscalationRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/import-history': typeof ImportHistoryRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRouteWithChildren
  '/trace': typeof TraceRoute
  '/api/alerts': typeof ApiAlertsRouteWithChildren
  '/api/timeline': typeof ApiTimelineRoute
  '/evidence/playback': typeof EvidencePlaybackRoute
  '/monitor/$id': typeof MonitorIdRoute
  '/monitor/devices': typeof MonitorDevicesRoute
  '/api/ai/root-cause-assist': typeof ApiAiRootCauseAssistRoute
  '/api/autopilot/recommendations': typeof ApiAutopilotRecommendationsRouteWithChildren
  '/api/autopilot/services': typeof ApiAutopilotServicesRouteWithChildren
  '/api/evidence/snapshots': typeof ApiEvidenceSnapshotsRoute
  '/api/monitor/devices': typeof ApiMonitorDevicesRouteWithChildren
  '/api/monitor/state': typeof ApiMonitorStateRoute
  '/api/monitor/status': typeof ApiMonitorStatusRoute
  '/api/system/correlation': typeof ApiSystemCorrelationRoute
  '/api/alerts/$id/ack': typeof ApiAlertsIdAckRoute
  '/api/alerts/$id/resolve': typeof ApiAlertsIdResolveRoute
  '/api/autopilot/recommendations/$id': typeof ApiAutopilotRecommendationsIdRouteWithChildren
  '/api/autopilot/services/$id': typeof ApiAutopilotServicesIdRoute
  '/api/autopilot/recommendations/$id/approve': typeof ApiAutopilotRecommendationsIdApproveRoute
  '/api/autopilot/recommendations/$id/reject': typeof ApiAutopilotRecommendationsIdRejectRoute
  '/api/autopilot/recommendations/from-alert/$alertId': typeof ApiAutopilotRecommendationsFromAlertAlertIdRoute
  '/api/monitor/devices/$id/correlate-recent': typeof ApiMonitorDevicesIdCorrelateRecentRoute
  '/api/monitor/devices/$id/log-paths': typeof ApiMonitorDevicesIdLogPathsRoute
  '/api/monitor/devices/$id/logs/recent': typeof ApiMonitorDevicesIdLogsRecentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-commander': typeof AiCommanderRoute
  '/autopilot': typeof AutopilotRoute
  '/diagnosis': typeof DiagnosisRoute
  '/escalation': typeof EscalationRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/import-history': typeof ImportHistoryRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRouteWithChildren
  '/trace': typeof TraceRoute
  '/api/alerts': typeof ApiAlertsRouteWithChildren
  '/api/timeline': typeof ApiTimelineRoute
  '/evidence/playback': typeof EvidencePlaybackRoute
  '/monitor/$id': typeof MonitorIdRoute
  '/monitor/devices': typeof MonitorDevicesRoute
  '/api/ai/root-cause-assist': typeof ApiAiRootCauseAssistRoute
  '/api/autopilot/recommendations': typeof ApiAutopilotRecommendationsRouteWithChildren
  '/api/autopilot/services': typeof ApiAutopilotServicesRouteWithChildren
  '/api/evidence/snapshots': typeof ApiEvidenceSnapshotsRoute
  '/api/monitor/devices': typeof ApiMonitorDevicesRouteWithChildren
  '/api/monitor/state': typeof ApiMonitorStateRoute
  '/api/monitor/status': typeof ApiMonitorStatusRoute
  '/api/system/correlation': typeof ApiSystemCorrelationRoute
  '/api/alerts/$id/ack': typeof ApiAlertsIdAckRoute
  '/api/alerts/$id/resolve': typeof ApiAlertsIdResolveRoute
  '/api/autopilot/recommendations/$id': typeof ApiAutopilotRecommendationsIdRouteWithChildren
  '/api/autopilot/services/$id': typeof ApiAutopilotServicesIdRoute
  '/api/autopilot/recommendations/$id/approve': typeof ApiAutopilotRecommendationsIdApproveRoute
  '/api/autopilot/recommendations/$id/reject': typeof ApiAutopilotRecommendationsIdRejectRoute
  '/api/autopilot/recommendations/from-alert/$alertId': typeof ApiAutopilotRecommendationsFromAlertAlertIdRoute
  '/api/monitor/devices/$id/correlate-recent': typeof ApiMonitorDevicesIdCorrelateRecentRoute
  '/api/monitor/devices/$id/log-paths': typeof ApiMonitorDevicesIdLogPathsRoute
  '/api/monitor/devices/$id/logs/recent': typeof ApiMonitorDevicesIdLogsRecentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-commander': typeof AiCommanderRoute
  '/autopilot': typeof AutopilotRoute
  '/diagnosis': typeof DiagnosisRoute
  '/escalation': typeof EscalationRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/import-history': typeof ImportHistoryRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRouteWithChildren
  '/trace': typeof TraceRoute
  '/api/alerts': typeof ApiAlertsRouteWithChildren
  '/api/timeline': typeof ApiTimelineRoute
  '/evidence/playback': typeof EvidencePlaybackRoute
  '/monitor/$id': typeof MonitorIdRoute
  '/monitor/devices': typeof MonitorDevicesRoute
  '/api/ai/root-cause-assist': typeof ApiAiRootCauseAssistRoute
  '/api/autopilot/recommendations': typeof ApiAutopilotRecommendationsRouteWithChildren
  '/api/autopilot/services': typeof ApiAutopilotServicesRouteWithChildren
  '/api/evidence/snapshots': typeof ApiEvidenceSnapshotsRoute
  '/api/monitor/devices': typeof ApiMonitorDevicesRouteWithChildren
  '/api/monitor/state': typeof ApiMonitorStateRoute
  '/api/monitor/status': typeof ApiMonitorStatusRoute
  '/api/system/correlation': typeof ApiSystemCorrelationRoute
  '/api/alerts/$id/ack': typeof ApiAlertsIdAckRoute
  '/api/alerts/$id/resolve': typeof ApiAlertsIdResolveRoute
  '/api/autopilot/recommendations/$id': typeof ApiAutopilotRecommendationsIdRouteWithChildren
  '/api/autopilot/services/$id': typeof ApiAutopilotServicesIdRoute
  '/api/autopilot/recommendations/$id/approve': typeof ApiAutopilotRecommendationsIdApproveRoute
  '/api/autopilot/recommendations/$id/reject': typeof ApiAutopilotRecommendationsIdRejectRoute
  '/api/autopilot/recommendations/from-alert/$alertId': typeof ApiAutopilotRecommendationsFromAlertAlertIdRoute
  '/api/monitor/devices/$id/correlate-recent': typeof ApiMonitorDevicesIdCorrelateRecentRoute
  '/api/monitor/devices/$id/log-paths': typeof ApiMonitorDevicesIdLogPathsRoute
  '/api/monitor/devices/$id/logs/recent': typeof ApiMonitorDevicesIdLogsRecentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-commander'
    | '/autopilot'
    | '/diagnosis'
    | '/escalation'
    | '/evidence'
    | '/import-history'
    | '/logs'
    | '/monitor'
    | '/trace'
    | '/api/alerts'
    | '/api/timeline'
    | '/evidence/playback'
    | '/monitor/$id'
    | '/monitor/devices'
    | '/api/ai/root-cause-assist'
    | '/api/autopilot/recommendations'
    | '/api/autopilot/services'
    | '/api/evidence/snapshots'
    | '/api/monitor/devices'
    | '/api/monitor/state'
    | '/api/monitor/status'
    | '/api/system/correlation'
    | '/api/alerts/$id/ack'
    | '/api/alerts/$id/resolve'
    | '/api/autopilot/recommendations/$id'
    | '/api/autopilot/services/$id'
    | '/api/autopilot/recommendations/$id/approve'
    | '/api/autopilot/recommendations/$id/reject'
    | '/api/autopilot/recommendations/from-alert/$alertId'
    | '/api/monitor/devices/$id/correlate-recent'
    | '/api/monitor/devices/$id/log-paths'
    | '/api/monitor/devices/$id/logs/recent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-commander'
    | '/autopilot'
    | '/diagnosis'
    | '/escalation'
    | '/evidence'
    | '/import-history'
    | '/logs'
    | '/monitor'
    | '/trace'
    | '/api/alerts'
    | '/api/timeline'
    | '/evidence/playback'
    | '/monitor/$id'
    | '/monitor/devices'
    | '/api/ai/root-cause-assist'
    | '/api/autopilot/recommendations'
    | '/api/autopilot/services'
    | '/api/evidence/snapshots'
    | '/api/monitor/devices'
    | '/api/monitor/state'
    | '/api/monitor/status'
    | '/api/system/correlation'
    | '/api/alerts/$id/ack'
    | '/api/alerts/$id/resolve'
    | '/api/autopilot/recommendations/$id'
    | '/api/autopilot/services/$id'
    | '/api/autopilot/recommendations/$id/approve'
    | '/api/autopilot/recommendations/$id/reject'
    | '/api/autopilot/recommendations/from-alert/$alertId'
    | '/api/monitor/devices/$id/correlate-recent'
    | '/api/monitor/devices/$id/log-paths'
    | '/api/monitor/devices/$id/logs/recent'
  id:
    | '__root__'
    | '/'
    | '/ai-commander'
    | '/autopilot'
    | '/diagnosis'
    | '/escalation'
    | '/evidence'
    | '/import-history'
    | '/logs'
    | '/monitor'
    | '/trace'
    | '/api/alerts'
    | '/api/timeline'
    | '/evidence/playback'
    | '/monitor/$id'
    | '/monitor/devices'
    | '/api/ai/root-cause-assist'
    | '/api/autopilot/recommendations'
    | '/api/autopilot/services'
    | '/api/evidence/snapshots'
    | '/api/monitor/devices'
    | '/api/monitor/state'
    | '/api/monitor/status'
    | '/api/system/correlation'
    | '/api/alerts/$id/ack'
    | '/api/alerts/$id/resolve'
    | '/api/autopilot/recommendations/$id'
    | '/api/autopilot/services/$id'
    | '/api/autopilot/recommendations/$id/approve'
    | '/api/autopilot/recommendations/$id/reject'
    | '/api/autopilot/recommendations/from-alert/$alertId'
    | '/api/monitor/devices/$id/correlate-recent'
    | '/api/monitor/devices/$id/log-paths'
    | '/api/monitor/devices/$id/logs/recent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCommanderRoute: typeof AiCommanderRoute
  AutopilotRoute: typeof AutopilotRoute
  DiagnosisRoute: typeof DiagnosisRoute
  EscalationRoute: typeof EscalationRoute
  EvidenceRoute: typeof EvidenceRouteWithChildren
  ImportHistoryRoute: typeof ImportHistoryRoute
  LogsRoute: typeof LogsRoute
  MonitorRoute: typeof MonitorRouteWithChildren
  TraceRoute: typeof TraceRoute
  ApiAlertsRoute: typeof ApiAlertsRouteWithChildren
  ApiTimelineRoute: typeof ApiTimelineRoute
  ApiAiRootCauseAssistRoute: typeof ApiAiRootCauseAssistRoute
  ApiAutopilotRecommendationsRoute: typeof ApiAutopilotRecommendationsRouteWithChildren
  ApiAutopilotServicesRoute: typeof ApiAutopilotServicesRouteWithChildren
  ApiEvidenceSnapshotsRoute: typeof ApiEvidenceSnapshotsRoute
  ApiMonitorDevicesRoute: typeof ApiMonitorDevicesRouteWithChildren
  ApiMonitorStateRoute: typeof ApiMonitorStateRoute
  ApiMonitorStatusRoute: typeof ApiMonitorStatusRoute
  ApiSystemCorrelationRoute: typeof ApiSystemCorrelationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-history': {
      id: '/import-history'
      path: '/import-history'
      fullPath: '/import-history'
      preLoaderRoute: typeof ImportHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalation': {
      id: '/escalation'
      path: '/escalation'
      fullPath: '/escalation'
      preLoaderRoute: typeof EscalationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-commander': {
      id: '/ai-commander'
      path: '/ai-commander'
      fullPath: '/ai-commander'
      preLoaderRoute: typeof AiCommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/devices': {
      id: '/monitor/devices'
      path: '/devices'
      fullPath: '/monitor/devices'
      preLoaderRoute: typeof MonitorDevicesRouteImport
      parentRoute: typeof MonitorRoute
    }
    '/monitor/$id': {
      id: '/monitor/$id'
      path: '/$id'
      fullPath: '/monitor/$id'
      preLoaderRoute: typeof MonitorIdRouteImport
      parentRoute: typeof MonitorRoute
    }
    '/evidence/playback': {
      id: '/evidence/playback'
      path: '/playback'
      fullPath: '/evidence/playback'
      preLoaderRoute: typeof EvidencePlaybackRouteImport
      parentRoute: typeof EvidenceRoute
    }
    '/api/timeline': {
      id: '/api/timeline'
      path: '/api/timeline'
      fullPath: '/api/timeline'
      preLoaderRoute: typeof ApiTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/correlation': {
      id: '/api/system/correlation'
      path: '/api/system/correlation'
      fullPath: '/api/system/correlation'
      preLoaderRoute: typeof ApiSystemCorrelationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitor/status': {
      id: '/api/monitor/status'
      path: '/api/monitor/status'
      fullPath: '/api/monitor/status'
      preLoaderRoute: typeof ApiMonitorStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitor/state': {
      id: '/api/monitor/state'
      path: '/api/monitor/state'
      fullPath: '/api/monitor/state'
      preLoaderRoute: typeof ApiMonitorStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitor/devices': {
      id: '/api/monitor/devices'
      path: '/api/monitor/devices'
      fullPath: '/api/monitor/devices'
      preLoaderRoute: typeof ApiMonitorDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence/snapshots': {
      id: '/api/evidence/snapshots'
      path: '/api/evidence/snapshots'
      fullPath: '/api/evidence/snapshots'
      preLoaderRoute: typeof ApiEvidenceSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autopilot/services': {
      id: '/api/autopilot/services'
      path: '/api/autopilot/services'
      fullPath: '/api/autopilot/services'
      preLoaderRoute: typeof ApiAutopilotServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autopilot/recommendations': {
      id: '/api/autopilot/recommendations'
      path: '/api/autopilot/recommendations'
      fullPath: '/api/autopilot/recommendations'
      preLoaderRoute: typeof ApiAutopilotRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/root-cause-assist': {
      id: '/api/ai/root-cause-assist'
      path: '/api/ai/root-cause-assist'
      fullPath: '/api/ai/root-cause-assist'
      preLoaderRoute: typeof ApiAiRootCauseAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autopilot/services/$id': {
      id: '/api/autopilot/services/$id'
      path: '/$id'
      fullPath: '/api/autopilot/services/$id'
      preLoaderRoute: typeof ApiAutopilotServicesIdRouteImport
      parentRoute: typeof ApiAutopilotServicesRoute
    }
    '/api/autopilot/recommendations/$id': {
      id: '/api/autopilot/recommendations/$id'
      path: '/$id'
      fullPath: '/api/autopilot/recommendations/$id'
      preLoaderRoute: typeof ApiAutopilotRecommendationsIdRouteImport
      parentRoute: typeof ApiAutopilotRecommendationsRoute
    }
    '/api/alerts/$id/resolve': {
      id: '/api/alerts/$id/resolve'
      path: '/$id/resolve'
      fullPath: '/api/alerts/$id/resolve'
      preLoaderRoute: typeof ApiAlertsIdResolveRouteImport
      parentRoute: typeof ApiAlertsRoute
    }
    '/api/alerts/$id/ack': {
      id: '/api/alerts/$id/ack'
      path: '/$id/ack'
      fullPath: '/api/alerts/$id/ack'
      preLoaderRoute: typeof ApiAlertsIdAckRouteImport
      parentRoute: typeof ApiAlertsRoute
    }
    '/api/monitor/devices/$id/log-paths': {
      id: '/api/monitor/devices/$id/log-paths'
      path: '/$id/log-paths'
      fullPath: '/api/monitor/devices/$id/log-paths'
      preLoaderRoute: typeof ApiMonitorDevicesIdLogPathsRouteImport
      parentRoute: typeof ApiMonitorDevicesRoute
    }
    '/api/monitor/devices/$id/correlate-recent': {
      id: '/api/monitor/devices/$id/correlate-recent'
      path: '/$id/correlate-recent'
      fullPath: '/api/monitor/devices/$id/correlate-recent'
      preLoaderRoute: typeof ApiMonitorDevicesIdCorrelateRecentRouteImport
      parentRoute: typeof ApiMonitorDevicesRoute
    }
    '/api/autopilot/recommendations/from-alert/$alertId': {
      id: '/api/autopilot/recommendations/from-alert/$alertId'
      path: '/from-alert/$alertId'
      fullPath: '/api/autopilot/recommendations/from-alert/$alertId'
      preLoaderRoute: typeof ApiAutopilotRecommendationsFromAlertAlertIdRouteImport
      parentRoute: typeof ApiAutopilotRecommendationsRoute
    }
    '/api/autopilot/recommendations/$id/reject': {
      id: '/api/autopilot/recommendations/$id/reject'
      path: '/reject'
      fullPath: '/api/autopilot/recommendations/$id/reject'
      preLoaderRoute: typeof ApiAutopilotRecommendationsIdRejectRouteImport
      parentRoute: typeof ApiAutopilotRecommendationsIdRoute
    }
    '/api/autopilot/recommendations/$id/approve': {
      id: '/api/autopilot/recommendations/$id/approve'
      path: '/approve'
      fullPath: '/api/autopilot/recommendations/$id/approve'
      preLoaderRoute: typeof ApiAutopilotRecommendationsIdApproveRouteImport
      parentRoute: typeof ApiAutopilotRecommendationsIdRoute
    }
    '/api/monitor/devices/$id/logs/recent': {
      id: '/api/monitor/devices/$id/logs/recent'
      path: '/$id/logs/recent'
      fullPath: '/api/monitor/devices/$id/logs/recent'
      preLoaderRoute: typeof ApiMonitorDevicesIdLogsRecentRouteImport
      parentRoute: typeof ApiMonitorDevicesRoute
    }
  }
}

interface EvidenceRouteChildren {
  EvidencePlaybackRoute: typeof EvidencePlaybackRoute
}

const EvidenceRouteChildren: EvidenceRouteChildren = {
  EvidencePlaybackRoute: EvidencePlaybackRoute,
}

const EvidenceRouteWithChildren = EvidenceRoute._addFileChildren(
  EvidenceRouteChildren,
)

interface MonitorRouteChildren {
  MonitorIdRoute: typeof MonitorIdRoute
  MonitorDevicesRoute: typeof MonitorDevicesRoute
}

const MonitorRouteChildren: MonitorRouteChildren = {
  MonitorIdRoute: MonitorIdRoute,
  MonitorDevicesRoute: MonitorDevicesRoute,
}

const MonitorRouteWithChildren =
  MonitorRoute._addFileChildren(MonitorRouteChildren)

interface ApiAlertsRouteChildren {
  ApiAlertsIdAckRoute: typeof ApiAlertsIdAckRoute
  ApiAlertsIdResolveRoute: typeof ApiAlertsIdResolveRoute
}

const ApiAlertsRouteChildren: ApiAlertsRouteChildren = {
  ApiAlertsIdAckRoute: ApiAlertsIdAckRoute,
  ApiAlertsIdResolveRoute: ApiAlertsIdResolveRoute,
}

const ApiAlertsRouteWithChildren = ApiAlertsRoute._addFileChildren(
  ApiAlertsRouteChildren,
)

interface ApiAutopilotRecommendationsIdRouteChildren {
  ApiAutopilotRecommendationsIdApproveRoute: typeof ApiAutopilotRecommendationsIdApproveRoute
  ApiAutopilotRecommendationsIdRejectRoute: typeof ApiAutopilotRecommendationsIdRejectRoute
}

const ApiAutopilotRecommendationsIdRouteChildren: ApiAutopilotRecommendationsIdRouteChildren =
  {
    ApiAutopilotRecommendationsIdApproveRoute:
      ApiAutopilotRecommendationsIdApproveRoute,
    ApiAutopilotRecommendationsIdRejectRoute:
      ApiAutopilotRecommendationsIdRejectRoute,
  }

const ApiAutopilotRecommendationsIdRouteWithChildren =
  ApiAutopilotRecommendationsIdRoute._addFileChildren(
    ApiAutopilotRecommendationsIdRouteChildren,
  )

interface ApiAutopilotRecommendationsRouteChildren {
  ApiAutopilotRecommendationsIdRoute: typeof ApiAutopilotRecommendationsIdRouteWithChildren
  ApiAutopilotRecommendationsFromAlertAlertIdRoute: typeof ApiAutopilotRecommendationsFromAlertAlertIdRoute
}

const ApiAutopilotRecommendationsRouteChildren: ApiAutopilotRecommendationsRouteChildren =
  {
    ApiAutopilotRecommendationsIdRoute:
      ApiAutopilotRecommendationsIdRouteWithChildren,
    ApiAutopilotRecommendationsFromAlertAlertIdRoute:
      ApiAutopilotRecommendationsFromAlertAlertIdRoute,
  }

const ApiAutopilotRecommendationsRouteWithChildren =
  ApiAutopilotRecommendationsRoute._addFileChildren(
    ApiAutopilotRecommendationsRouteChildren,
  )

interface ApiAutopilotServicesRouteChildren {
  ApiAutopilotServicesIdRoute: typeof ApiAutopilotServicesIdRoute
}

const ApiAutopilotServicesRouteChildren: ApiAutopilotServicesRouteChildren = {
  ApiAutopilotServicesIdRoute: ApiAutopilotServicesIdRoute,
}

const ApiAutopilotServicesRouteWithChildren =
  ApiAutopilotServicesRoute._addFileChildren(ApiAutopilotServicesRouteChildren)

interface ApiMonitorDevicesRouteChildren {
  ApiMonitorDevicesIdCorrelateRecentRoute: typeof ApiMonitorDevicesIdCorrelateRecentRoute
  ApiMonitorDevicesIdLogPathsRoute: typeof ApiMonitorDevicesIdLogPathsRoute
  ApiMonitorDevicesIdLogsRecentRoute: typeof ApiMonitorDevicesIdLogsRecentRoute
}

const ApiMonitorDevicesRouteChildren: ApiMonitorDevicesRouteChildren = {
  ApiMonitorDevicesIdCorrelateRecentRoute:
    ApiMonitorDevicesIdCorrelateRecentRoute,
  ApiMonitorDevicesIdLogPathsRoute: ApiMonitorDevicesIdLogPathsRoute,
  ApiMonitorDevicesIdLogsRecentRoute: ApiMonitorDevicesIdLogsRecentRoute,
}

const ApiMonitorDevicesRouteWithChildren =
  ApiMonitorDevicesRoute._addFileChildren(ApiMonitorDevicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCommanderRoute: AiCommanderRoute,
  AutopilotRoute: AutopilotRoute,
  DiagnosisRoute: DiagnosisRoute,
  EscalationRoute: EscalationRoute,
  EvidenceRoute: EvidenceRouteWithChildren,
  ImportHistoryRoute: ImportHistoryRoute,
  LogsRoute: LogsRoute,
  MonitorRoute: MonitorRouteWithChildren,
  TraceRoute: TraceRoute,
  ApiAlertsRoute: ApiAlertsRouteWithChildren,
  ApiTimelineRoute: ApiTimelineRoute,
  ApiAiRootCauseAssistRoute: ApiAiRootCauseAssistRoute,
  ApiAutopilotRecommendationsRoute:
    ApiAutopilotRecommendationsRouteWithChildren,
  ApiAutopilotServicesRoute: ApiAutopilotServicesRouteWithChildren,
  ApiEvidenceSnapshotsRoute: ApiEvidenceSnapshotsRoute,
  ApiMonitorDevicesRoute: ApiMonitorDevicesRouteWithChildren,
  ApiMonitorStateRoute: ApiMonitorStateRoute,
  ApiMonitorStatusRoute: ApiMonitorStatusRoute,
  ApiSystemCorrelationRoute: ApiSystemCorrelationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
