/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ImportHistoryRouteImport } from './routes/import-history'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as EscalationRouteImport } from './routes/escalation'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as AiCommanderRouteImport } from './routes/ai-commander'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonitorDevicesRouteImport } from './routes/monitor.devices'
import { Route as MonitorIdRouteImport } from './routes/monitor.$id'
import { Route as EvidencePlaybackRouteImport } from './routes/evidence.playback'
import { Route as ApiMonitorStatusRouteImport } from './routes/api/monitor.status'
import { Route as ApiMonitorStateRouteImport } from './routes/api/monitor.state'
import { Route as ApiMonitorDevicesRouteImport } from './routes/api/monitor.devices'
import { Route as ApiAutopilotServicesRouteImport } from './routes/api/autopilot.services'
import { Route as ApiAutopilotServicesIdRouteImport } from './routes/api/autopilot.services.$id'
import { Route as ApiMonitorDevicesIdLogsRecentRouteImport } from './routes/api/monitor.devices.$id.logs.recent'

const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportHistoryRoute = ImportHistoryRouteImport.update({
  id: '/import-history',
  path: '/import-history',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationRoute = EscalationRouteImport.update({
  id: '/escalation',
  path: '/escalation',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCommanderRoute = AiCommanderRouteImport.update({
  id: '/ai-commander',
  path: '/ai-commander',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorDevicesRoute = MonitorDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => MonitorRoute,
} as any)
const MonitorIdRoute = MonitorIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MonitorRoute,
} as any)
const EvidencePlaybackRoute = EvidencePlaybackRouteImport.update({
  id: '/playback',
  path: '/playback',
  getParentRoute: () => EvidenceRoute,
} as any)
const ApiMonitorStatusRoute = ApiMonitorStatusRouteImport.update({
  id: '/api/monitor/status',
  path: '/api/monitor/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitorStateRoute = ApiMonitorStateRouteImport.update({
  id: '/api/monitor/state',
  path: '/api/monitor/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitorDevicesRoute = ApiMonitorDevicesRouteImport.update({
  id: '/api/monitor/devices',
  path: '/api/monitor/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutopilotServicesRoute = ApiAutopilotServicesRouteImport.update({
  id: '/api/autopilot/services',
  path: '/api/autopilot/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutopilotServicesIdRoute = ApiAutopilotServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAutopilotServicesRoute,
} as any)
const ApiMonitorDevicesIdLogsRecentRoute =
  ApiMonitorDevicesIdLogsRecentRouteImport.update({
    id: '/$id/logs/recent',
    path: '/$id/logs/recent',
    getParentRoute: () => ApiMonitorDevicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-commander': typeof AiCommanderRoute
  '/autopilot': typeof AutopilotRoute
  '/diagnosis': typeof DiagnosisRoute
  '/escalation': typeof EscalationRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/import-history': typeof ImportHistoryRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRouteWithChildren
  '/trace': typeof TraceRoute
  '/evidence/playback': typeof EvidencePlaybackRoute
  '/monitor/$id': typeof MonitorIdRoute
  '/monitor/devices': typeof MonitorDevicesRoute
  '/api/autopilot/services': typeof ApiAutopilotServicesRouteWithChildren
  '/api/monitor/devices': typeof ApiMonitorDevicesRouteWithChildren
  '/api/monitor/state': typeof ApiMonitorStateRoute
  '/api/monitor/status': typeof ApiMonitorStatusRoute
  '/api/autopilot/services/$id': typeof ApiAutopilotServicesIdRoute
  '/api/monitor/devices/$id/logs/recent': typeof ApiMonitorDevicesIdLogsRecentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-commander': typeof AiCommanderRoute
  '/autopilot': typeof AutopilotRoute
  '/diagnosis': typeof DiagnosisRoute
  '/escalation': typeof EscalationRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/import-history': typeof ImportHistoryRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRouteWithChildren
  '/trace': typeof TraceRoute
  '/evidence/playback': typeof EvidencePlaybackRoute
  '/monitor/$id': typeof MonitorIdRoute
  '/monitor/devices': typeof MonitorDevicesRoute
  '/api/autopilot/services': typeof ApiAutopilotServicesRouteWithChildren
  '/api/monitor/devices': typeof ApiMonitorDevicesRouteWithChildren
  '/api/monitor/state': typeof ApiMonitorStateRoute
  '/api/monitor/status': typeof ApiMonitorStatusRoute
  '/api/autopilot/services/$id': typeof ApiAutopilotServicesIdRoute
  '/api/monitor/devices/$id/logs/recent': typeof ApiMonitorDevicesIdLogsRecentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-commander': typeof AiCommanderRoute
  '/autopilot': typeof AutopilotRoute
  '/diagnosis': typeof DiagnosisRoute
  '/escalation': typeof EscalationRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/import-history': typeof ImportHistoryRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRouteWithChildren
  '/trace': typeof TraceRoute
  '/evidence/playback': typeof EvidencePlaybackRoute
  '/monitor/$id': typeof MonitorIdRoute
  '/monitor/devices': typeof MonitorDevicesRoute
  '/api/autopilot/services': typeof ApiAutopilotServicesRouteWithChildren
  '/api/monitor/devices': typeof ApiMonitorDevicesRouteWithChildren
  '/api/monitor/state': typeof ApiMonitorStateRoute
  '/api/monitor/status': typeof ApiMonitorStatusRoute
  '/api/autopilot/services/$id': typeof ApiAutopilotServicesIdRoute
  '/api/monitor/devices/$id/logs/recent': typeof ApiMonitorDevicesIdLogsRecentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-commander'
    | '/autopilot'
    | '/diagnosis'
    | '/escalation'
    | '/evidence'
    | '/import-history'
    | '/logs'
    | '/monitor'
    | '/trace'
    | '/evidence/playback'
    | '/monitor/$id'
    | '/monitor/devices'
    | '/api/autopilot/services'
    | '/api/monitor/devices'
    | '/api/monitor/state'
    | '/api/monitor/status'
    | '/api/autopilot/services/$id'
    | '/api/monitor/devices/$id/logs/recent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-commander'
    | '/autopilot'
    | '/diagnosis'
    | '/escalation'
    | '/evidence'
    | '/import-history'
    | '/logs'
    | '/monitor'
    | '/trace'
    | '/evidence/playback'
    | '/monitor/$id'
    | '/monitor/devices'
    | '/api/autopilot/services'
    | '/api/monitor/devices'
    | '/api/monitor/state'
    | '/api/monitor/status'
    | '/api/autopilot/services/$id'
    | '/api/monitor/devices/$id/logs/recent'
  id:
    | '__root__'
    | '/'
    | '/ai-commander'
    | '/autopilot'
    | '/diagnosis'
    | '/escalation'
    | '/evidence'
    | '/import-history'
    | '/logs'
    | '/monitor'
    | '/trace'
    | '/evidence/playback'
    | '/monitor/$id'
    | '/monitor/devices'
    | '/api/autopilot/services'
    | '/api/monitor/devices'
    | '/api/monitor/state'
    | '/api/monitor/status'
    | '/api/autopilot/services/$id'
    | '/api/monitor/devices/$id/logs/recent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCommanderRoute: typeof AiCommanderRoute
  AutopilotRoute: typeof AutopilotRoute
  DiagnosisRoute: typeof DiagnosisRoute
  EscalationRoute: typeof EscalationRoute
  EvidenceRoute: typeof EvidenceRouteWithChildren
  ImportHistoryRoute: typeof ImportHistoryRoute
  LogsRoute: typeof LogsRoute
  MonitorRoute: typeof MonitorRouteWithChildren
  TraceRoute: typeof TraceRoute
  ApiAutopilotServicesRoute: typeof ApiAutopilotServicesRouteWithChildren
  ApiMonitorDevicesRoute: typeof ApiMonitorDevicesRouteWithChildren
  ApiMonitorStateRoute: typeof ApiMonitorStateRoute
  ApiMonitorStatusRoute: typeof ApiMonitorStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-history': {
      id: '/import-history'
      path: '/import-history'
      fullPath: '/import-history'
      preLoaderRoute: typeof ImportHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalation': {
      id: '/escalation'
      path: '/escalation'
      fullPath: '/escalation'
      preLoaderRoute: typeof EscalationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-commander': {
      id: '/ai-commander'
      path: '/ai-commander'
      fullPath: '/ai-commander'
      preLoaderRoute: typeof AiCommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/devices': {
      id: '/monitor/devices'
      path: '/devices'
      fullPath: '/monitor/devices'
      preLoaderRoute: typeof MonitorDevicesRouteImport
      parentRoute: typeof MonitorRoute
    }
    '/monitor/$id': {
      id: '/monitor/$id'
      path: '/$id'
      fullPath: '/monitor/$id'
      preLoaderRoute: typeof MonitorIdRouteImport
      parentRoute: typeof MonitorRoute
    }
    '/evidence/playback': {
      id: '/evidence/playback'
      path: '/playback'
      fullPath: '/evidence/playback'
      preLoaderRoute: typeof EvidencePlaybackRouteImport
      parentRoute: typeof EvidenceRoute
    }
    '/api/monitor/status': {
      id: '/api/monitor/status'
      path: '/api/monitor/status'
      fullPath: '/api/monitor/status'
      preLoaderRoute: typeof ApiMonitorStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitor/state': {
      id: '/api/monitor/state'
      path: '/api/monitor/state'
      fullPath: '/api/monitor/state'
      preLoaderRoute: typeof ApiMonitorStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitor/devices': {
      id: '/api/monitor/devices'
      path: '/api/monitor/devices'
      fullPath: '/api/monitor/devices'
      preLoaderRoute: typeof ApiMonitorDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autopilot/services': {
      id: '/api/autopilot/services'
      path: '/api/autopilot/services'
      fullPath: '/api/autopilot/services'
      preLoaderRoute: typeof ApiAutopilotServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autopilot/services/$id': {
      id: '/api/autopilot/services/$id'
      path: '/$id'
      fullPath: '/api/autopilot/services/$id'
      preLoaderRoute: typeof ApiAutopilotServicesIdRouteImport
      parentRoute: typeof ApiAutopilotServicesRoute
    }
    '/api/monitor/devices/$id/logs/recent': {
      id: '/api/monitor/devices/$id/logs/recent'
      path: '/$id/logs/recent'
      fullPath: '/api/monitor/devices/$id/logs/recent'
      preLoaderRoute: typeof ApiMonitorDevicesIdLogsRecentRouteImport
      parentRoute: typeof ApiMonitorDevicesRoute
    }
  }
}

interface EvidenceRouteChildren {
  EvidencePlaybackRoute: typeof EvidencePlaybackRoute
}

const EvidenceRouteChildren: EvidenceRouteChildren = {
  EvidencePlaybackRoute: EvidencePlaybackRoute,
}

const EvidenceRouteWithChildren = EvidenceRoute._addFileChildren(
  EvidenceRouteChildren,
)

interface MonitorRouteChildren {
  MonitorIdRoute: typeof MonitorIdRoute
  MonitorDevicesRoute: typeof MonitorDevicesRoute
}

const MonitorRouteChildren: MonitorRouteChildren = {
  MonitorIdRoute: MonitorIdRoute,
  MonitorDevicesRoute: MonitorDevicesRoute,
}

const MonitorRouteWithChildren =
  MonitorRoute._addFileChildren(MonitorRouteChildren)

interface ApiAutopilotServicesRouteChildren {
  ApiAutopilotServicesIdRoute: typeof ApiAutopilotServicesIdRoute
}

const ApiAutopilotServicesRouteChildren: ApiAutopilotServicesRouteChildren = {
  ApiAutopilotServicesIdRoute: ApiAutopilotServicesIdRoute,
}

const ApiAutopilotServicesRouteWithChildren =
  ApiAutopilotServicesRoute._addFileChildren(ApiAutopilotServicesRouteChildren)

interface ApiMonitorDevicesRouteChildren {
  ApiMonitorDevicesIdLogsRecentRoute: typeof ApiMonitorDevicesIdLogsRecentRoute
}

const ApiMonitorDevicesRouteChildren: ApiMonitorDevicesRouteChildren = {
  ApiMonitorDevicesIdLogsRecentRoute: ApiMonitorDevicesIdLogsRecentRoute,
}

const ApiMonitorDevicesRouteWithChildren =
  ApiMonitorDevicesRoute._addFileChildren(ApiMonitorDevicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCommanderRoute: AiCommanderRoute,
  AutopilotRoute: AutopilotRoute,
  DiagnosisRoute: DiagnosisRoute,
  EscalationRoute: EscalationRoute,
  EvidenceRoute: EvidenceRouteWithChildren,
  ImportHistoryRoute: ImportHistoryRoute,
  LogsRoute: LogsRoute,
  MonitorRoute: MonitorRouteWithChildren,
  TraceRoute: TraceRoute,
  ApiAutopilotServicesRoute: ApiAutopilotServicesRouteWithChildren,
  ApiMonitorDevicesRoute: ApiMonitorDevicesRouteWithChildren,
  ApiMonitorStateRoute: ApiMonitorStateRoute,
  ApiMonitorStatusRoute: ApiMonitorStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
