/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as EscalationRouteImport } from './routes/escalation'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as IndexRouteImport } from './routes/index'

const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationRoute = EscalationRouteImport.update({
  id: '/escalation',
  path: '/escalation',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autopilot': typeof AutopilotRoute
  '/diagnosis': typeof DiagnosisRoute
  '/escalation': typeof EscalationRoute
  '/logs': typeof LogsRoute
  '/trace': typeof TraceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autopilot': typeof AutopilotRoute
  '/diagnosis': typeof DiagnosisRoute
  '/escalation': typeof EscalationRoute
  '/logs': typeof LogsRoute
  '/trace': typeof TraceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autopilot': typeof AutopilotRoute
  '/diagnosis': typeof DiagnosisRoute
  '/escalation': typeof EscalationRoute
  '/logs': typeof LogsRoute
  '/trace': typeof TraceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autopilot'
    | '/diagnosis'
    | '/escalation'
    | '/logs'
    | '/trace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/autopilot' | '/diagnosis' | '/escalation' | '/logs' | '/trace'
  id:
    | '__root__'
    | '/'
    | '/autopilot'
    | '/diagnosis'
    | '/escalation'
    | '/logs'
    | '/trace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutopilotRoute: typeof AutopilotRoute
  DiagnosisRoute: typeof DiagnosisRoute
  EscalationRoute: typeof EscalationRoute
  LogsRoute: typeof LogsRoute
  TraceRoute: typeof TraceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalation': {
      id: '/escalation'
      path: '/escalation'
      fullPath: '/escalation'
      preLoaderRoute: typeof EscalationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutopilotRoute: AutopilotRoute,
  DiagnosisRoute: DiagnosisRoute,
  EscalationRoute: EscalationRoute,
  LogsRoute: LogsRoute,
  TraceRoute: TraceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
